### PR TITLE
[WIP] Use In-App-Update Library to check version on Android

### PR DESCRIPTION
**Pull request by dazza5000**

### CODE REVIEW

**Comment by dazza5000** [comment]
Thank you for the existing upgrader plugin.

I know this PR is not the best, please comment on which direction you would like to see it take and I can maybe help with the changes. Thank you!

**Comment by larryaasen** [comment]
This PR includes an internal plugin. Maybe the plugin should be its own package.

**Comment by darran-kelinske-fivestars** [comment]
It could be included as a dependency and called through to. This is your project and I want to respect the direction you want to take with it. The advantage of using the in app update api's is that the end user doesn't need to manage an appcast implementation.

**Comment by andreadelfante** [comment]
Hi guys, may I ask why the author closed this PR?

**Comment by dazza5000** [comment]
I might have misunderstood, but I closed it because I thought the repo owner was indicating to put the changes into another plugin. You can always take the PR and apply it to a fork. The fork for the PR worked on another project.

**Pull request closed without merging**
