### PR TITLE
Adding support for custom logic to enforce update.

### LINKED ISSUE #297: Adding support for custom logic to enforce update.
Introducing the ShouldBeBlocking Callback

Incorporating custom logic to determine whether an update should be enforced or not can greatly enhance the functionality of the upgrader package. The ShouldBeBlocking callback provides a valuable solution to this requirement.

Consider the following code snippet:

```dart
Upgrader(
  child: MyApp(),
  shouldBeBlocking: (installedVersion, storeVersion) {
    // Add your logic here to compare the installedVersion and storeVersion
    // Return true if the update should be enforced, false otherwise.
  },
);
```

This simple yet powerful approach enables you to enforce updates based on predefined conditions that are less likely to change over subsequent app updates. For instance, you can enforce major releases or crucial hotfix patches, while allowing users to make their own decision regarding minor updates.

The ShouldBeBlocking callback offers several advantages over alternatives like AppCast or minAppVersion. Configuring those alternatives manually can be time-consuming and may require rewriting significant parts of the code. Moreover, AppCast setup can pose challenges, especially for beginners, due to its complexities and intricate configuration. On the other hand, relying solely on the minimum app version specified in the app store description carries risks, as it disperses the enforcement logic outside of the app itself. It's worth noting that the individuals responsible for writing app store descriptions may not be the developers themselves, introducing potential discrepancies.

### PR DESCRIPTION
**Pull request by hasanmhallak**
closes #297

### CODE REVIEW

**Comment by hasanmhallak** [comment]
@larryaasen could you please review this PR so I can safely include it in production?

**Comment by larryaasen** [comment]
There is a new version https://pub.dev/packages/upgrader/versions/9.0.0-alpha.1 that is in test and provides a way to handle this. Look at the examples included with the package.

**Comment by hasanmhallak** [comment]
hey @larryaasen I've just checked out the new version and I've found that you add a way to customize the alert/card, but still there is no access to the installed version or the store version. As I mentioned this [issue](github.com/larryaasen/upgrader/issues/297) it's important to have access to `installedVersion` and `storeVersion` so we can dynamically  decide whether we want to force an update or not.

**Comment by larryaasen** [comment]
@hasanmhallak You should try this:
```
final upgrader = MyUpgrader(debugLogging: true);
...

UpgradeAlert(upgrader: upgrader);
...

class MyUpgrader extends Upgrader {
  MyUpgrader({super.debugLogging});

  @override
  bool isUpdateAvailable() {
    final appStoreVersion = currentAppStoreVersion();
    final installedVersion = currentInstalledVersion();
    print('appStoreVersion=$appStoreVersion');
    print('installedVersion=$installedVersion');
    return super.isUpdateAvailable();
  }
}
```
In that example you subclass `Upgrader` and override `isUpdateAvailable` and you have access to the app store and installed versions. Does that work for you?

**Comment by hasanmhallak** [comment]
@larryaasen Thanks for the quick response. 

Unfortunately this snippet won't solve the problem. The requirements I have is to check if the store has a major version release and force the user to update by hiding the `ignore` and `later` buttons.

But I've just looked at extending the `Upgrader` class and found that I can override the `showIgnore` & `showLater` getters and still have access to `currentAppStoreVersion()` & `currentInstalledVersion()` so I guess this will do. I'll try to override them with our custom logic and see if this would solve the problem. Thank you.

**Comment by larryaasen** [comment]
> @larryaasen Thanks for the quick response.
> 
> Unfortunately this snippet won't solve the problem. The requirements I have is to check if the store has a major version release and force the user to update by hiding the `ignore` and `later` buttons.
> 
> But I've just looked at extending the `Upgrader` class and found that I can override the `showIgnore` & `showLater` getters and still have access to `currentAppStoreVersion()` & `currentInstalledVersion()` so I guess this will do. I'll try to override them with our custom logic and see if this would solve the problem. Thank you.

I think you should be able to solve your custom upgrade logic the way you described. There are endless combinations of logic choices and they cannot all be added to this package, so having the ability to extend it works well.

**Comment by hasanmhallak** [comment]
This is not relevant any more as you can now override the `Upgrader` class as below:

```
class AppUpgrader extends Upgrader {
  @override
  bool blocked() {
    final installed =
        int.tryParse(currentInstalledVersion?.split('.').first ?? '');
    final store = int.tryParse(currentAppStoreVersion?.split('.').first ?? '');

    if (installed == null || store == null) return false;

    // block only if it's a major update.;
    return store > installed;
  }
}

```

So I'll close this.

**Pull request closed without merging**
