### PR TITLE
Added new language translations for Danish ('da').

### PR DESCRIPTION
**Pull request by Ruukas97**
Added localization for Danish (of Denmark)

### CODE REVIEW

**Comment by larryaasen** [comment]
Thanks for this Danish translation. This looks very good.

**Comment by larryaasen** [comment]
The translation for LATER was missing so I used SENERE.

**Comment by larryaasen** [comment]
@Ruukas97  Why did you not translate `Release Notes` to `Udgivelses noter`?

**Comment by Ruukas97** [comment]
Thank you.
In Danish, a lot of terms are borrowed from English rather than using or creating a Danish word. I believe `Release notes` in a Danish context is more unambiguous.
In our app, we decided to hide release notes, as we consider them to be technical details. Additionally, release notes are usually written in English.

We use borrowed words such as:
- computer
- mail
- printer
- release
- upload
- software

I did find a few examples of "Udgivelsesnoter", though. That would be fine to use as well.
[Apple example](https://support.apple.com/da-dk/HT202998)
[Evernote example](https://help.evernote.com/hc/da/articles/1500001700002-Tidligere-udgivelsesnoter-for-Evernote-til-Mac)

**Pull request merged**
