### PR TITLE
fix: strict null safety, and doesn't render when message is `null`

### PR DESCRIPTION
**Pull request by cipchk**

### CODE REVIEW

**Comment by cipchk** [comment]
Hi, @larryaasen  Can you review it? We need it.

**Comment by larryaasen** [comment]
This is a good PR but there is a lot to review here. Need more time.

**Comment by larryaasen** [comment]
@cipchk Can you provide an example of this issue?

**Comment by larryaasen** [comment]
This PR cannot be merged. Either make a smaller PR or close this.

**Pull request closed without merging**
