### PR TITLE
Custom dialog support

### PR DESCRIPTION
**Pull request by hvg2416**
Hi! First of all, I have to say, this is such a useful package. Thank you so much for this package. 

## Problem Statement
Although the package fulfills the basic needs of most of the apps but for certain brand-centric apps, we need to use a very different UI from those standard materials & Cupertino alert dialogs.

### Choices users have in such a case:
- Build a whole new package to cater to the need which the upgrader already fulfills & add their custom dialog widget.
- Go through the upgrader's codebase & try to customize it as per the need

## Solution proposed:
- It will be very useful if we allow users to pass a method that will then be called inside the upgrader at a suitable time. This allows users to show literally any kind of UI they want to.

Method signature
```dart
Widget getCustomDialog(BuildContext context,
    {String title,
    String message,
    String releaseNotes,
    void Function() onUserIgnored,
    void Function() onUserLater,
    void Function() onUserUpdated});
```
or
with null safety
```dart
Widget getCustomDialog(BuildContext context,
    {String? title,
    String? message,
    String? releaseNotes,
    void Function()? onUserIgnored,
    void Function()? onUserLater,
    void Function()? onUserUpdated});
```

## Changes in this pull request:
- [x] Added logic to show custom dialog
- [x] Updated the example/main.dart to show usage of custom dialog widget

@larryaasen I hope you will find this contribution a valid one. Looking forward to contributing to this amazing package!

### CODE REVIEW

**Comment by larryaasen** [comment]
@hvg2416 I really like this idea of allowing custom dialogs, and it is very important to architect this well. I don't know if this is the best solution. I need to think about this a little more.

**Comment by stilbu** [comment]
Awesome, exactly what we need aswell. Was looking into this :)

**Comment by hvg2416** [comment]
@stilbu For time being, if you want to use this feature, you can out my fork of this awesome package here https://pub.dev/packages/custom_upgrader

**Comment by H-ishak** [comment]
@larryaasen  this will be very awesome but i think that this solution isn't the best i hope you can find a better solution quickly

**Comment by larryaasen** [comment]
@hvg2416 There is a new version https://pub.dev/packages/upgrader/versions/9.0.0-alpha.1 that is in test and provides a way to handle this. Look at the examples included with the package.

**Comment by larryaasen** [comment]
@hvg2416 Look at the latest version of this package with a latest customization options. I think it now meets your needs. If not, please open a new issue with your details.

**Pull request closed without merging**
