### PR TITLE
intercept dialog display

### PR DESCRIPTION
**Pull request by nathanielajayi7**
- Intercept display of dialog (useful for custom UI dialogs)

### CODE REVIEW

**Comment by larryaasen** [comment]
There is a new version https://pub.dev/packages/upgrader/versions/9.0.0-alpha.1 that is in test and provides a way to handle this. Look at the examples included with the package.

**Comment by larryaasen** [comment]
There is a new version https://pub.dev/packages/upgrader/versions/9.0.0-alpha.1 that is in test and provides a way to handle this. Look at the examples included with the package.

**Comment by larryaasen** [comment]
@nathanielajayi7 Look at the latest version of this package with a latest customization options. I think it now meets your needs. If not, please open a new issue with your details.

**Comment by nathanielajayi7** [comment]
@larryaasen hi, didn't see previous notifications - I think the new additions are more than enough for my use case

**Pull request closed without merging**
