### PR TITLE
Update pubspec.yaml

### PR DESCRIPTION
**Pull request by Aniketkhote**

### CODE REVIEW

**Comment by larryaasen** [comment]
@Aniketkhote What is the basis for this proposed change? I see in the Dart package `appengine` that they use single quotes:
https://github.com/dart-lang/appengine/blob/0e85dae475369188b2e633a17a17e11fb8e591a6/pubspec.yaml#L13

**Comment by Aniketkhote** [comment]
I've updated the packages device_info_plus and package_info_plus to their latest versions due to encountering a conflict issue during the update in my project

**Comment by larryaasen** [comment]
Thanks for this PR and the suggestion to upgrade the versions for those packages. Due to the other changes added to the PR, I don't want to merge this. I will just make the version changes myself.

**Comment by larryaasen** [comment]
You get see the change now in pub.dev: https://pub.dev/packages/upgrader

**Pull request closed without merging**
