### PR TITLE
upgrade version from [2.17.1] to  [2.18.4] for incompatible versions

### PR DESCRIPTION
**Pull request by itsmelaxman**
Upgrader package is incompatible with my version...so, I Just upgrade the version to 2.18.4 from 2.17.1

### CODE REVIEW

**Comment by larryaasen** [comment]
@itsmelaxman What was not compatible with upgrader?

**Comment by itsmelaxman** [comment]
> @itsmelaxman What was not compatible with upgrader?

I was not able to place the upgrader package in my pubspec.yaml due to package low sdk version. so, I just change the sdk version of root folder from [2.17.1] to [2.18.4] and push here.

**Comment by itsmelaxman** [comment]
> > @itsmelaxman What was not compatible with upgrader?
> 
> I was not able to place the upgrader package in my pubspec.yaml due to package low sdk version. so, I just change the sdk version of root folder from [2.17.1] to [2.18.4] and push here.

for no

**Comment by larryaasen** [comment]
That will eliminate many users from utilizing a new version of upgrader who have not yet upgraded their Dart SDK to 2.18.4. How do you plan to continue to support those users?

**Pull request closed without merging**
