### PR TITLE
Pass the language code to iTunes search api to get localized release notes

### LINKED ISSUE #314: languageCode doesnt override the default one
Hello 
 im trying to use languageCode to override my device language, for example my mobile has English language as a default language, when i change my `languageCode` to 'ar' , it doesnt work, still messages are in English not arabic

### PR DESCRIPTION
**Pull request by Add00w**
fixes #314

### CODE REVIEW

**Comment by larryaasen** [comment]
@Add00w Thanks for this pull request. Did you see that the unit tests are not passing?

**Comment by Add00w** [comment]
> @Add00w Thanks for this pull request. Did you see that the unit tests are not passing?

Yes, I will fix

**Comment by larryaasen** [comment]
@Add00w I would like to get this PR merged, but it now has a merge conflict. Can you resolve that?

**Comment by ibraheemalayan** [comment]
@Add00w 
@larryaasen 

I solved the merge conflicts and did the changes required to be compatible with version 10.3.0 in PR #439 
It has passed all the tests and is ready to be merged

**Pull request closed without merging**
